import turtle as tom
tom.speed(0)
tom.begin_fill()
tom.color('silver')
tom.bgcolor('blue')
tom.pencolor('silver')
tom.penup()
tom.goto(-350,-100)
tom.pendown()
tom.width(10)

tom.right(25)
for i in range(3):
    tom.forward(500)
    tom.left(90)
# tom.forward(500)
# tom.left(90)
# tom.forward(500)
# tom.left(90)
tom.forward(500)
tom.end_fill()
tom.begin_fill()
tom.color('blue')
tom.penup()
tom.goto(-135,-10)
tom.pendown()

for i in range(4):
    tom.left(90)
    tom.forward(175)
# tom.left(90)
# tom.forward(175)
# tom.left(90)
# tom.forward(175)
# tom.left(90)
# tom.forward(175)
# tom.left(90)
# tom.forward(175)
tom.end_fill()
tom.done()
